"use client";

import { useRef, useState, type FormEvent } from "react";
import { api } from "@/lib/gov/client";

interface Msg {
  role: "user" | "assistant";
  text: string;
}

export function AssistantTab({ workspaceId, workspaceName }: { workspaceId: string; workspaceName: string }) {
  const [messages, setMessages] = useState<Msg[]>([]);
  const [question, setQuestion] = useState("");
  const [asking, setAsking] = useState(false);
  const endRef = useRef<HTMLDivElement>(null);

  async function handleAsk(e: FormEvent) {
    e.preventDefault();
    const q = question.trim();
    if (!q || asking) return;
    setMessages((prev) => [...prev, { role: "user", text: q }]);
    setQuestion("");
    setAsking(true);
    try {
      const { answer } = await api.askWorkspaceQuestion(workspaceId, q);
      setMessages((prev) => [...prev, { role: "assistant", text: answer }]);
    } catch {
      setMessages((prev) => [...prev, { role: "assistant", text: "Sorry, I couldn't answer that just now." }]);
    } finally {
      setAsking(false);
      setTimeout(() => endRef.current?.scrollIntoView({ behavior: "smooth" }), 50);
    }
  }

  return (
    <div className="mx-auto flex max-w-2xl flex-col rounded-sm border border-register-line bg-register-panel shadow-card">
      <div className="border-b border-register-line px-5 py-4">
        <h3 className="font-serif-display text-base font-semibold text-register-navy">AI Research Assistant</h3>
        <p className="mt-1 text-xs leading-relaxed text-register-ink/55">
          Answers are generated by a deterministic, rule-based engine grounded entirely in{" "}
          <strong>{workspaceName}</strong>'s own data — its tasks, findings, linked evidence, policy notes,
          discussions and linked districts/parcels. This is not a general AI chatbot and no external AI call is
          made; if the workspace doesn't hold the answer, it says so rather than guessing.
        </p>
      </div>

      <div className="min-h-[260px] flex-1 space-y-3 overflow-y-auto px-5 py-4">
        {messages.length === 0 && (
          <div className="space-y-1.5 text-xs text-register-ink/50">
            <p>Try asking:</p>
            <ul className="list-disc space-y-1 pl-4">
              <li>&quot;What is the progress on this workspace?&quot;</li>
              <li>&quot;What findings have been recorded?&quot;</li>
              <li>&quot;Who is on the team?&quot;</li>
              <li>&quot;What documents are linked?&quot;</li>
            </ul>
          </div>
        )}
        {messages.map((m, i) => (
          <div
            key={i}
            className={`max-w-[90%] rounded-sm px-3 py-2 text-sm leading-relaxed ${
              m.role === "user" ? "ml-auto bg-register-navy text-white" : "bg-register-bg text-register-ink/85"
            }`}
          >
            {m.text}
          </div>
        ))}
        {asking && <div className="max-w-[90%] rounded-sm bg-register-bg px-3 py-2 text-sm text-register-ink/50">Thinking…</div>}
        <div ref={endRef} />
      </div>

      <form onSubmit={handleAsk} className="flex gap-2 border-t border-register-line p-3">
        <input
          value={question}
          onChange={(e) => setQuestion(e.target.value)}
          placeholder="Ask about this workspace's data…"
          className="flex-1 rounded-sm border border-register-line bg-white px-3 py-2 text-sm focus:border-register-navy focus:outline-none focus:ring-2 focus:ring-register-navy/15"
        />
        <button type="submit" disabled={asking || !question.trim()} className="rounded-sm bg-register-navy px-3.5 py-2 text-sm font-medium text-white hover:bg-register-navy2 disabled:opacity-50">
          Ask
        </button>
      </form>
    </div>
  );
}
